#!/usr/bin/env python3
"""
Configure local operator activation (only when NOT using the license service).

Your password unlocks PrimeNet for NCM_ACTIVATION_PERIOD_DAYS (default 180 ≈ 6 months).

For remote licensing, run license_service/ instead and set NCM_LICENSE_SERVER_URL
in PrimeNet .env — no local password file needed on PrimeNet.

  python scripts/set_activation_password.py            # set / change password
  python scripts/set_activation_password.py --unlock   # unlock from CLI
"""

from __future__ import annotations

import argparse
import getpass
import os
import sys

_PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from core.activation_gate import (  # noqa: E402
    activation_period_days,
    hash_password_for_config,
    unlock,
)

_SECRETS_PATH = os.path.join(_PROJECT_ROOT, "core", "activation_secrets_local.py")


def _prompt_password_twice() -> str:
    while True:
        p1 = getpass.getpass("Operator password (min 8 chars): ")
        p2 = getpass.getpass("Confirm password: ")
        if p1 != p2:
            print("Passwords do not match. Try again.")
            continue
        if len(p1) < 8:
            print("Password must be at least 8 characters.")
            continue
        return p1


def write_secrets(password: str) -> None:
    password_hash_hex, signing_key_hex = hash_password_for_config(password)
    content = f'''"""
Local operator activation secrets — DO NOT COMMIT (see .gitignore).
Generated by scripts/set_activation_password.py
"""

PASSWORD_HASH_HEX = "{password_hash_hex}"
SIGNING_KEY_HEX = "{signing_key_hex}"
'''
    with open(_SECRETS_PATH, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"[OK] Wrote {_SECRETS_PATH}")


def main() -> int:
    parser = argparse.ArgumentParser(description="PrimeNet operator activation setup")
    parser.add_argument(
        "--unlock",
        action="store_true",
        help="Unlock the application for the configured period after entering the password",
    )
    args = parser.parse_args()

    if (os.getenv("NCM_LICENSE_SERVER_URL") or "").strip():
        print("NCM_LICENSE_SERVER_URL is set — use /activation or license_service unlock.")
        if args.unlock:
            password = getpass.getpass("Operator password: ")
            status = unlock(password)
            print(f"[OK] Unlocked until {status.get('expires_at')}")
            print(f"     Days remaining: {status.get('days_remaining')}")
        return 0

    if not os.path.isfile(_SECRETS_PATH):
        print("No activation secrets file yet — creating one.")
        write_secrets(_prompt_password_twice())
    elif not args.unlock:
        overwrite = input("Secrets file exists. Overwrite password? [y/N]: ").strip().lower()
        if overwrite == "y":
            write_secrets(_prompt_password_twice())
        else:
            print("Kept existing secrets.")

    period = activation_period_days()
    if args.unlock:
        password = getpass.getpass("Operator password: ")
        status = unlock(password)
        print(f"[OK] Unlocked until {status.get('expires_at')} ({period} day period)")
        print(f"     Days remaining: {status.get('days_remaining')}")
    else:
        print()
        print(f"Unlock period: {period} days (set NCM_ACTIVATION_PERIOD_DAYS in .env to change)")
        print("Next: unlock from the terminal or web UI:")
        print("  python scripts/set_activation_password.py --unlock")
        print("  http://localhost:5000/activation")
        print()
        print("Keep core/activation_secrets_local.py private — never commit or share it.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
