"""Unit tests for SQLite→Postgres SQL adaptation and domain routing (no Postgres server)."""

from __future__ import annotations

import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from db.app_sql import adapt_sqlite_app_sql, qmark_to_percent, rewrite_pragma
from db.pg_domains import enabled_groups, is_domain_postgresql, schema_for_sqlite_path


def _clear_pg_env():
    for key in ('NCM_DATABASE_URL', 'NCM_APP_DATABASE_URL', 'APP_DATABASE_URL', 'NCM_PG_DOMAINS'):
        os.environ.pop(key, None)


class AppSqlTests(unittest.TestCase):
    def test_qmark_ignores_string_literals(self):
        sql = "SELECT * FROM t WHERE name = '?' AND id = ?"
        self.assertEqual(qmark_to_percent(sql), "SELECT * FROM t WHERE name = '?' AND id = %s")

    def test_autoincrement(self):
        sql = 'id INTEGER PRIMARY KEY AUTOINCREMENT,'
        out = adapt_sqlite_app_sql(sql)
        self.assertIn('GENERATED BY DEFAULT AS IDENTITY', out)
        self.assertNotIn('AUTOINCREMENT', out)

    def test_boolean_defaults(self):
        self.assertIn('BOOLEAN DEFAULT TRUE', adapt_sqlite_app_sql('is_active BOOLEAN DEFAULT 1'))
        self.assertIn('BOOLEAN DEFAULT FALSE', adapt_sqlite_app_sql('is_shared BOOLEAN DEFAULT 0'))

    def test_on_conflict_spacing(self):
        sql = 'ON CONFLICT(user_id) DO UPDATE SET x = excluded.x'
        out = adapt_sqlite_app_sql(sql)
        self.assertIn('ON CONFLICT (user_id)', out)
        self.assertIn('EXCLUDED.x', out)

    def test_last_insert_rowid(self):
        self.assertEqual(
            adapt_sqlite_app_sql('SELECT last_insert_rowid()'),
            'SELECT lastval()',
        )

    def test_pragma_table_info(self):
        out = rewrite_pragma('PRAGMA table_info("4G_CELLS_HOURLY")')
        self.assertIsNotNone(out)
        self.assertIn('information_schema.columns', out)
        self.assertIn("table_name = '4G_CELLS_HOURLY'", out)

    def test_pragma_journal_noop(self):
        self.assertEqual(rewrite_pragma('PRAGMA journal_mode=WAL'), 'SELECT 1 WHERE false')

    def test_sqlite_master_table_list(self):
        sql = (
            "SELECT name FROM sqlite_master WHERE type='table' "
            "AND name NOT LIKE 'sqlite_%' ORDER BY name"
        )
        out = adapt_sqlite_app_sql(sql)
        self.assertIn('information_schema.tables', out)
        self.assertNotIn('sqlite_master', out)

    def test_unique_on_conflict_replace(self):
        sql = 'UNIQUE (cell_name, timestamp) ON CONFLICT REPLACE'
        out = adapt_sqlite_app_sql(sql)
        self.assertIn('UNIQUE (cell_name, timestamp)', out)
        self.assertNotIn('ON CONFLICT REPLACE', out)

    def test_insert_or_replace_pm(self):
        sql = 'INSERT OR REPLACE INTO "4G_CELLS_HOURLY" (cell_name, timestamp, kpi) VALUES (?, ?, ?)'
        out = adapt_sqlite_app_sql(sql)
        self.assertIn('INSERT INTO', out)
        self.assertIn('ON CONFLICT (cell_name, timestamp) DO UPDATE SET', out)
        self.assertIn('%s', out)
        self.assertNotIn('?', out)

    def test_insert_or_ignore(self):
        sql = 'INSERT OR IGNORE INTO cells (cell_name) VALUES (?)'
        out = adapt_sqlite_app_sql(sql)
        self.assertIn('ON CONFLICT DO NOTHING', out)


class DomainRoutingTests(unittest.TestCase):
    def setUp(self):
        _clear_pg_env()
        self.addCleanup(_clear_pg_env)

    def test_default_no_postgres(self):
        self.assertEqual(enabled_groups(), frozenset())
        self.assertFalse(is_domain_postgresql('app'))
        self.assertFalse(is_domain_postgresql('pm'))
        self.assertIsNone(schema_for_sqlite_path('C:/nope/metadata.db'))

    def test_app_url_only_enables_app(self):
        os.environ['NCM_APP_DATABASE_URL'] = 'postgresql://u:p@127.0.0.1:5432/primenet'
        self.assertEqual(enabled_groups(), frozenset({'app'}))
        self.assertTrue(is_domain_postgresql('app'))
        self.assertFalse(is_domain_postgresql('metadata'))
        self.assertFalse(is_domain_postgresql('pm'))

    def test_database_url_enables_all_groups(self):
        os.environ['NCM_DATABASE_URL'] = 'postgresql://u:p@127.0.0.1:5432/primenet'
        groups = enabled_groups()
        self.assertIn('app', groups)
        self.assertIn('metadata', groups)
        self.assertIn('pm', groups)
        self.assertIn('neighbors', groups)
        self.assertIn('groups', groups)
        self.assertIn('balance', groups)

    def test_pg_domains_subset(self):
        os.environ['NCM_DATABASE_URL'] = 'postgresql://u:p@127.0.0.1:5432/primenet'
        os.environ['NCM_PG_DOMAINS'] = 'metadata,pm'
        self.assertEqual(enabled_groups(), frozenset({'metadata', 'pm'}))
        self.assertTrue(is_domain_postgresql('pm_nokia_hourly'))
        self.assertFalse(is_domain_postgresql('app'))


class SqliteAppDbStillWorks(unittest.TestCase):
    def test_connect_app_sqlite_default(self):
        _clear_pg_env()
        os.environ['NCM_SKIP_ACTIVATION'] = '1'
        from db.runtime import connect_app, connect_metadata, is_app_postgresql, is_postgresql

        self.assertFalse(is_app_postgresql())
        self.assertFalse(is_postgresql())
        conn = connect_app()
        try:
            row = conn.execute('SELECT 1 AS n').fetchone()
            self.assertEqual(int(row['n'] if row['n'] is not None else row[0]), 1)
        finally:
            conn.close()
        meta = connect_metadata()
        try:
            row = meta.execute('SELECT 1 AS n').fetchone()
            self.assertEqual(int(row['n'] if row['n'] is not None else row[0]), 1)
        finally:
            meta.close()


if __name__ == '__main__':
    unittest.main()
