"""Unit tests for SQLite→Postgres SQL adaptation and domain routing (no Postgres server)."""

from __future__ import annotations

import os
import sys
import unittest

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from db.app_sql import adapt_sqlite_app_sql, qmark_to_percent, rewrite_pragma
from db.pg_domains import enabled_groups, is_domain_postgresql, schema_for_sqlite_path


def _clear_pg_env():
    for key in ('NCM_DATABASE_URL', 'NCM_APP_DATABASE_URL', 'APP_DATABASE_URL', 'NCM_PG_DOMAINS'):
        os.environ.pop(key, None)


class AppSqlTests(unittest.TestCase):
    def test_qmark_ignores_string_literals(self):
        sql = "SELECT * FROM t WHERE name = '?' AND id = ?"
        self.assertEqual(qmark_to_percent(sql), "SELECT * FROM t WHERE name = '?' AND id = %s")

    def test_qmark_escapes_literal_percent(self):
        sql = "SELECT name FROM t WHERE name LIKE 't_%' AND id = ?"
        out = qmark_to_percent(sql)
        self.assertIn("LIKE 't_%%'", out)
        self.assertIn('%s', out)
        self.assertNotIn("got '%'", out)

    def test_adapt_escapes_percent_in_column_names(self):
        """PM KPI columns like Availability(%) must not become psycopg placeholders."""
        sql = (
            'CREATE TABLE t ("Availability(%)" TEXT, "UL_BLER_%" TEXT, '
            '"CSSR (%)" DOUBLE PRECISION)'
        )
        out = adapt_sqlite_app_sql(sql)
        self.assertIn('"Availability(%%)"', out)
        self.assertIn('"UL_BLER_%%"', out)
        self.assertIn('"CSSR (%%)"', out)
        ins = 'INSERT INTO t ("Availability(%)", "UL_BLER_%") VALUES (?, ?)'
        adapted = adapt_sqlite_app_sql(ins)
        self.assertIn('"Availability(%%)"', adapted)
        self.assertIn('VALUES (%s, %s)', adapted)

    def test_adapt_is_idempotent(self):
        cases = [
            "SELECT * FROM users WHERE username = ? AND is_active = 1",
            'INSERT INTO "t" ("cell", "CSSR(%)") VALUES (?, ?)',
            "SELECT name FROM t WHERE name LIKE '%sector%' AND id = ?",
            "SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 't_%'",
            'INSERT OR REPLACE INTO "4G" (cell_name, timestamp, kpi) VALUES (?, ?, ?)',
        ]
        for sql in cases:
            once = adapt_sqlite_app_sql(sql)
            self.assertEqual(adapt_sqlite_app_sql(once), once, sql)

    def test_percent_s_inside_literal_is_not_placeholder(self):
        out = qmark_to_percent("SELECT 1 FROM t WHERE name LIKE '%sector%' AND id = ?")
        self.assertIn("LIKE '%%sector%%'", out)
        self.assertTrue(out.endswith('id = %s'))

    def test_autoincrement(self):
        sql = 'id INTEGER PRIMARY KEY AUTOINCREMENT,'
        out = adapt_sqlite_app_sql(sql)
        self.assertIn('GENERATED BY DEFAULT AS IDENTITY', out)
        self.assertNotIn('AUTOINCREMENT', out)

    def test_boolean_defaults(self):
        self.assertIn('BOOLEAN DEFAULT TRUE', adapt_sqlite_app_sql('is_active BOOLEAN DEFAULT 1'))
        self.assertIn('BOOLEAN DEFAULT FALSE', adapt_sqlite_app_sql('is_shared BOOLEAN DEFAULT 0'))

    def test_on_conflict_spacing(self):
        sql = 'ON CONFLICT(user_id) DO UPDATE SET x = excluded.x'
        out = adapt_sqlite_app_sql(sql)
        self.assertIn('ON CONFLICT (user_id)', out)
        self.assertIn('EXCLUDED.x', out)

    def test_last_insert_rowid(self):
        self.assertEqual(
            adapt_sqlite_app_sql('SELECT last_insert_rowid()'),
            'SELECT lastval()',
        )

    def test_pragma_table_info(self):
        out = rewrite_pragma('PRAGMA table_info("4G_CELLS_HOURLY")')
        self.assertIsNotNone(out)
        self.assertIn('information_schema.columns', out)
        self.assertIn("table_name = '4G_CELLS_HOURLY'", out)

    def test_pragma_journal_noop(self):
        self.assertEqual(rewrite_pragma('PRAGMA journal_mode=WAL'), 'SELECT 1 WHERE false')

    def test_sqlite_master_table_list(self):
        sql = (
            "SELECT name FROM sqlite_master WHERE type='table' "
            "AND name NOT LIKE 'sqlite_%' ORDER BY name"
        )
        out = adapt_sqlite_app_sql(sql)
        self.assertIn('information_schema.tables', out)
        self.assertNotIn('sqlite_master', out)

    def test_sqlite_master_table_exists(self):
        sql = "SELECT 1 FROM sqlite_master WHERE type='table' AND name=? LIMIT 1"
        out = adapt_sqlite_app_sql(sql)
        self.assertIn('information_schema.tables', out)
        self.assertIn('table_name = %s', out)
        self.assertNotIn('sqlite_master', out)

    def test_sqlite_master_like_filter(self):
        sql = "SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 't_%'"
        out = adapt_sqlite_app_sql(sql)
        self.assertIn('information_schema.tables', out)
        self.assertIn('table_name LIKE', out)
        self.assertNotIn('sqlite_master', out)
        # Literal LIKE wildcards must be %% for psycopg
        self.assertIn("LIKE 't_%%'", out)

    def test_unique_on_conflict_replace(self):
        sql = 'UNIQUE (cell_name, timestamp) ON CONFLICT REPLACE'
        out = adapt_sqlite_app_sql(sql)
        self.assertIn('UNIQUE (cell_name, timestamp)', out)
        self.assertNotIn('ON CONFLICT REPLACE', out)

    def test_insert_or_replace_pm(self):
        sql = 'INSERT OR REPLACE INTO "4G_CELLS_HOURLY" (cell_name, timestamp, kpi) VALUES (?, ?, ?)'
        out = adapt_sqlite_app_sql(sql)
        self.assertIn('INSERT INTO', out)
        self.assertIn('ON CONFLICT (cell_name, timestamp) DO UPDATE SET', out)
        self.assertIn('%s', out)
        self.assertNotIn('?', out)

    def test_insert_or_ignore(self):
        sql = 'INSERT OR IGNORE INTO cells (cell_name) VALUES (?)'
        out = adapt_sqlite_app_sql(sql)
        self.assertIn('ON CONFLICT DO NOTHING', out)


class _RecordingRaw:
    def __init__(self):
        self.calls = []

    def execute(self, sql, params=None):
        self.calls.append((sql, params))

    def cursor(self):
        return self

    def executemany(self, sql, seq):
        self.calls.append((sql, list(seq)[0]))

    def close(self):
        pass


def _psycopg_final_sql(sql, params) -> str:
    from psycopg._queries import PostgresQuery
    from psycopg.adapt import Transformer

    q = PostgresQuery(Transformer())
    q.convert(sql, params)
    return q.query.decode()


class PercentColumnTests(unittest.TestCase):
    """PM counter headers like ``CSSR(%)`` must survive psycopg placeholder parsing."""

    def setUp(self):
        try:
            import psycopg  # noqa: F401
        except ImportError:
            self.skipTest('psycopg not installed')
        from db.runtime import PgConn

        self.raw = _RecordingRaw()
        self.conn = PgConn(self.raw)

    def test_insert_with_percent_column(self):
        self.conn.executemany('INSERT INTO "t" ("cell", "CSSR(%)") VALUES (?, ?)', [('A', 1.0)])
        sql, params = self.raw.calls[-1]
        self.assertEqual(
            _psycopg_final_sql(sql, params),
            'INSERT INTO "t" ("cell", "CSSR(%)") VALUES ($1, $2)',
        )

    def test_alter_add_percent_column_without_params(self):
        self.conn.execute('ALTER TABLE "t" ADD COLUMN "CSSR(%)" TEXT')
        sql, params = self.raw.calls[-1]
        self.assertIsNotNone(params)
        self.assertEqual(
            _psycopg_final_sql(sql, params),
            'ALTER TABLE "t" ADD COLUMN "CSSR(%)" TEXT',
        )

    def test_pre_adapted_sql_keeps_placeholders(self):
        from db.app_sql import adapt_sqlite_app_sql as adapt

        self.conn.cursor().execute(adapt('SELECT * FROM users WHERE username = ?'), ('admin',))
        sql, params = self.raw.calls[-1]
        self.assertEqual(
            _psycopg_final_sql(sql, params),
            'SELECT * FROM users WHERE username = $1',
        )

    def test_cursor_execute_without_params(self):
        self.conn.cursor().execute('CREATE TABLE "t" ("Drop Rate(%)" TEXT)')
        sql, params = self.raw.calls[-1]
        self.assertEqual(
            _psycopg_final_sql(sql, params),
            'CREATE TABLE "t" ("Drop Rate(%)" TEXT)',
        )


class DomainRoutingTests(unittest.TestCase):
    def setUp(self):
        _clear_pg_env()
        self.addCleanup(_clear_pg_env)

    def test_default_no_postgres(self):
        self.assertEqual(enabled_groups(), frozenset())
        self.assertFalse(is_domain_postgresql('app'))
        self.assertFalse(is_domain_postgresql('pm'))
        self.assertIsNone(schema_for_sqlite_path('C:/nope/metadata.db'))

    def test_app_url_only_enables_app(self):
        os.environ['NCM_APP_DATABASE_URL'] = 'postgresql://u:p@127.0.0.1:5432/primenet'
        self.assertEqual(enabled_groups(), frozenset({'app'}))
        self.assertTrue(is_domain_postgresql('app'))
        self.assertFalse(is_domain_postgresql('metadata'))
        self.assertFalse(is_domain_postgresql('pm'))

    def test_database_url_enables_all_groups(self):
        os.environ['NCM_DATABASE_URL'] = 'postgresql://u:p@127.0.0.1:5432/primenet'
        groups = enabled_groups()
        self.assertIn('app', groups)
        self.assertIn('metadata', groups)
        self.assertIn('pm', groups)
        self.assertIn('neighbors', groups)
        self.assertIn('groups', groups)
        self.assertIn('balance', groups)
        self.assertIn('femto', groups)
        self.assertIn('son_ml', groups)
        self.assertIn('nh_precalc', groups)
        self.assertIn('kpi_headers', groups)
        self.assertIn('cm', groups)
        self.assertIn('marketing', groups)

    def test_pg_domains_subset(self):
        os.environ['NCM_DATABASE_URL'] = 'postgresql://u:p@127.0.0.1:5432/primenet'
        os.environ['NCM_PG_DOMAINS'] = 'metadata,pm'
        self.assertEqual(enabled_groups(), frozenset({'metadata', 'pm'}))
        self.assertTrue(is_domain_postgresql('pm_nokia_hourly'))
        self.assertFalse(is_domain_postgresql('app'))


class SqliteAppDbStillWorks(unittest.TestCase):
    def test_require_postgres_url_without_env(self):
        _clear_pg_env()
        from db.pg_domains import require_postgres_url

        with self.assertRaises(RuntimeError) as ctx:
            require_postgres_url()
        self.assertIn('NCM_DATABASE_URL', str(ctx.exception))

    def test_use_sqlite_helper_always_false(self):
        _clear_pg_env()
        from db.runtime import use_sqlite_for_app_and_metadata

        self.assertFalse(use_sqlite_for_app_and_metadata())


if __name__ == '__main__':
    unittest.main()
